apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: spring-boot-vuejs
build:
  artifacts:
    - image: your-registry/spring-boot-vuejs
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: spring-boot-vuejs-service
    namespace: spring-boot-vuejs
    port: 8088
    localPort: 8088
profiles:
  - name: development
    activation:
      - command: dev
    build:
      artifacts:
        - image: your-registry/spring-boot-vuejs
          sync:
            manual:
              - src: backend/src/**/*.java
                dest: /app
    deploy:
      kubectl: {}
  - name: production
    build:
      artifacts:
        - image: your-registry/spring-boot-vuejs
          docker:
            dockerfile: Dockerfile
      tagPolicy:
        gitCommit: {}
    deploy:
      kubectl: {}
